# Generated by Django 5.0.6 on 2024-09-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='featured_image',
        ),
    ]
